name: Compilar e publicar no TestPyPI e no PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configura o Python
        uses: actions/setup-python@v5

      - name: Instalar ferramentas para compilação
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel twine build "numpy>=1.26"
          git submodule update --init --recursive

      - name: Rodando o cibuildwheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/tests

          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_SKIP: "*-musllinux_*"
      
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y gcc-gfortran openblas-devel lapack-devel
            
          CIBW_ENVIRONMENT_LINUX: 'LDFLAGS="-Wl,-rpath,\$ORIGIN -lopenblas -llapack"'

      - name: Subindo os artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: ./wheelhouse/*.whl
  
  publicar-testpypi:
    name: Publicar para o TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/ncorpos-utilidades-py

    permissions:
      id-token: write

    steps:
    - name: Baixando todas as dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
      
    - name: Publicando no TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publicar-pypi:
    name: >-
      Publicar para o PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ncorpos-utilidades-py
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Baixando todas as dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publicando no PyPI
      uses: pypa/gh-action-pypi-publish@release/v1